### ISSUE TITLE
hidpi-daemon TypeError: '<=' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by cjohnston1158** [pop-os/beta#127]
**How did you upgrade to 20.04? (Fresh install / Upgrade)**
Fresh
 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
apt policy hidpi-daemon 
hidpi-daemon:
  Installed: 18.04.5~1571160416~20.04~d1fa331

**Issue/Bug Description:**
May  4 04:02:02 kachemak hidpi-daemon.desktop[2985]: /usr/lib/hidpi-daemon/hidpi-daemon:91: PyGIDeprecationWarning: Since version 3.11, calling threads_init is no longer needed. See: https://wiki.gnome.org/PyGObject/Threading
May  4 04:02:02 kachemak hidpi-daemon.desktop[2985]:   GObject.threads_init()
May  4 04:02:02 kachemak hidpi-daemon.desktop[2985]: Traceback (most recent call last):
May  4 04:02:02 kachemak hidpi-daemon.desktop[2985]:   File "/usr/lib/python3/dist-packages/hidpidaemon/hidpidaemon2.py", line 461, in on_notification_mode
May  4 04:02:02 kachemak hidpi-daemon.desktop[2985]:     self.notification_update_scaling(restart=False)
May  4 04:02:02 kachemak hidpi-daemon.desktop[2985]:   File "/usr/lib/python3/dist-packages/hidpidaemon/hidpidaemon2.py", line 454, in notification_update_scaling
May  4 04:02:02 kachemak hidpi-daemon.desktop[2985]:     h.set_scaled_display_modes(notification=False)
May  4 04:02:02 kachemak hidpi-daemon.desktop[2985]:   File "/usr/lib/python3/dist-packages/hidpidaemon/hidpidaemon2.py", line 1343, in set_scaled_display_modes
May  4 04:02:02 kachemak hidpi-daemon.desktop[2985]:     self.set_display_scaling(display, layout, force=force)
May  4 04:02:02 kachemak hidpi-daemon.desktop[2985]:   File "/usr/lib/python3/dist-packages/hidpidaemon/hidpidaemon2.py", line 1255, in set_display_scaling
May  4 04:02:02 kachemak hidpi-daemon.desktop[2985]:     return self.set_display_scaling_xrandr(display, layout, force_lowdpi=force)
May  4 04:02:02 kachemak hidpi-daemon.desktop[2985]:   File "/usr/lib/python3/dist-packages/hidpidaemon/hidpidaemon2.py", line 1182, in set_display_scaling_xrandr
May  4 04:02:02 kachemak hidpi-daemon.desktop[2985]:     if saved_dpi <= 170 and force_lowdpi:
May  4 04:02:02 kachemak hidpi-daemon.desktop[2985]: TypeError: '<=' not supported between instances of 'NoneType' and 'int'

**Steps to reproduce (if you know):**
Received this while adjusting displays this morning.

**Expected behavior:**
Don't error

**Comment by brs17** [comment]
Thank you for filing this issue. Moving this issue to the hidpi daemon repository.
