### ISSUE TITLE
ua-timer.service failure

### ISSUE THREAD

**Issue by canadaduane** [pop-os/beta#396]
**How did you upgrade to 22.04? (Fresh install / Upgrade)**
Upgrade from 21.10
 

 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
Not sure

**Issue/Bug Description:**
I see the following error in the logs, indicating ua-timer cannot parse `/etc/os-release` properly:

```
Apr 13 11:37:31 pop-os systemd[1]: Starting Ubuntu Advantage Timer for running repeated jobs...
░░ Subject: A start job for unit ua-timer.service has begun execution
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit ua-timer.service has begun execution.
░░ 
░░ The job identifier is 2634.
Apr 13 11:37:31 pop-os python3[12162]: Traceback (most recent call last):
Apr 13 11:37:31 pop-os python3[12162]:   File "/usr/lib/ubuntu-advantage/timer.py", line 9, in <module>
Apr 13 11:37:31 pop-os python3[12162]:     from uaclient.cli import setup_logging
Apr 13 11:37:31 pop-os python3[12162]:   File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 22, in <module>
Apr 13 11:37:31 pop-os python3[12162]:     from uaclient import (
Apr 13 11:37:31 pop-os python3[12162]:   File "/usr/lib/python3/dist-packages/uaclient/security_status.py", line 11, in <module>
Apr 13 11:37:31 pop-os python3[12162]:     series = get_platform_info()["series"]
Apr 13 11:37:31 pop-os python3[12162]:   File "/usr/lib/python3/dist-packages/uaclient/util.py", line 303, in get_platform_info
Apr 13 11:37:31 pop-os python3[12162]:     raise RuntimeError(
Apr 13 11:37:31 pop-os python3[12162]: RuntimeError: Could not parse /etc/os-release VERSION: 22.04 LTS (modified to 22.04 LTS)
Apr 13 11:37:31 pop-os systemd[1]: ua-timer.service: Main process exited, code=exited, status=1/FAILURE

... later ...

Apr 13 11:37:31 pop-os systemd[1]: Failed to start Ubuntu Advantage Timer for running repeated jobs.

```

**Steps to reproduce (if you know):**

I'm not sure what triggers this--perhaps a cron job?

**Expected behavior:**
No error in logs.

**Comment by macuser10-6** [comment]
I ran into this issue as well. I believe it was something to do with a package called `pulseaudioi386`. 

`           Depends: pipewire but it is not going to be installed
               Depends: pipewire-audio-client-libraries but it is not going to be installed
               Depends: pipewire-pulse
               Depends: wireplumber but it is not going to be installed
               Conflicts: pulseaudio
               Recommends: io.elementary.sideload but it is not installable
               Recommends: gnome-remote-desktop but it is not going to be installed
               Recommends: gnome-shell-extension-prefs but it is not going to be installed
               Conflicts: pulseaudio:i386
`
After masking the service that was running I purged the pulse-audio package and after reboot the conflict is now gone and my system status is no longer showing degraded. 

I used the steps in this article to mask; https://askubuntu.com/questions/1371014/what-is-ubuntu-advantage-doing-on-my-fully-supported-20-04-box-what-is-it-che

**Comment by mmstick** [comment]
It's safe to mask or ignore the error. `ubuntu-advantage-tools` is now a `Depends` of `ubuntu-minimal` so it can't be removed. But it's also not compatible with the os-release file in Pop. This is another point for a desire to replace the `ubuntu-minimal` dependency with `pop-minimal`.

**Comment by kokizzu** [comment]
I can't find this anywhere 
```
$ sudo apt install pop-minimal
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package pop-minimal
```

**Comment by why-not-try-calmer** [comment]
> It's safe to mask or ignore the error. `ubuntu-advantage-tools` is now a `Depends` of `ubuntu-minimal` so it can't be removed. But it's also not compatible with the os-release file in Pop. This is another point for a desire to replace the `ubuntu-minimal` dependency with `pop-minimal`.

Wouldn't it be better to just shun the associated services and timer?

```
systemctl disable ua-license-check.path
systemctl disable ua-timer.service
systemctl disable ua-timer.timer
```

As per `systemctl list-dependencies < service > --all --reverse` none of them has any dependent.
